export const texts = {
  en: {
    'error.title': 'Something went wrong',
    'error.info': 'An error occured. Please reload the site and try again.',
    'error.button': 'Try Again',
    'loading.text': 'Loading...',
    'mainmenu.title': 'Welcome',
    'mainmenu.button.newgame': 'Click to play',
    'navbar.language.label': 'Change language',
    'navbar.color.label': 'Change color scheme',
    'game.question.effectiveness': '%s used %s',
    'game.status.fainted': '%s fainted',
    'game.status.switched': 'Go! %s',
    'gameover.title': 'Game Over',
    'gameover.text.blackout': 'you whited out...',
    'gameover.text.score': 'your final score is',
    'gameover.button.newgame': 'Try again',
    'gameover.button.mainmenu': 'Main Menu',
    'score.label': 'Score',
    'types.effectiveness.noeffect': 'No effect',
    'types.effectiveness.noteffective': 'Not very effective',
    'types.effectiveness.effective': 'Effective',
    'types.effectiveness.supereffective': 'Super effective',
    'mainmenu.difficulty.simple': 'Simple',
    'mainmenu.difficulty.expert': 'Expert',
  },
  de: {
    'error.title': 'Irgendetwas stimmt hier nicht',
    'error.info': 'Ein Fehler ist aufgetreten. Bitte lade die Seite neu und versuche es nochmal.',
    'error.button': 'Neuer Version',
    'loading.text': 'Wird geladen...',
    'mainmenu.title': 'Willkommen',
    'mainmenu.button.newgame': 'Neues Spiel',
    'navbar.language.label': 'Sprache wechseln',
    'navbar.color.label': 'Farbschema wechseln',
    'game.question.effectiveness': '%s setzt %s ein',
    'game.status.fainted': '%s ist besiegt',
    'game.status.switched': 'Los! %s',
    'gameover.title': 'Verloren',
    'gameover.text.blackout': 'Du hast keine kampffähigen Pokemon mehr...',
    'gameover.text.score': 'Dein Endergebnis ist',
    'gameover.button.newgame': 'Neues Spiel',
    'gameover.button.mainmenu': 'Hauptmenü',
    'score.label': 'Punktzahl',
    'types.effectiveness.noeffect': 'Kein Effekt',
    'types.effectiveness.noteffective': 'Nicht sehr effektiv',
    'types.effectiveness.effective': 'Effektiv',
    'types.effectiveness.supereffective': 'Sehr effektiv',
    'mainmenu.difficulty.simple': 'Einfach',
    'mainmenu.difficulty.expert': 'Experte',
  },
  es: {
    'error.title': 'Algo salió mal',
    'error.info': 'Se produjo un error. Recarga la página e inténtalo de nuevo.',
    'error.button': 'Intentar de nuevo',
    'loading.text': 'Cargando...',
    'mainmenu.title': 'Bienvenido',
    'mainmenu.button.newgame': 'Toca para jugar',
    'navbar.language.label': 'Cambiar idioma',
    'navbar.color.label': 'Cambiar esquema de color',
    'game.question.effectiveness': '%s usó %s',
    'game.status.fainted': '%s se debilitó',
    'game.status.switched': '¡Adelante! %s',
    'gameover.title': 'Fin de la partida',
    'gameover.text.blackout': 'te has quedado sin Pokémon útiles...',
    'gameover.text.score': 'tu puntuación final es',
    'gameover.button.newgame': 'Intentar de nuevo',
    'gameover.button.mainmenu': 'Menú principal',
    'score.label': 'Puntuación',
    'types.effectiveness.noeffect': 'No tiene efecto',
    'types.effectiveness.noteffective': 'No es muy eficaz',
    'types.effectiveness.effective': 'Eficaz',
    'types.effectiveness.supereffective': 'Es muy eficaz',
    'mainmenu.difficulty.simple': 'Fácil',
    'mainmenu.difficulty.expert': 'Experto',
  },
  fr: {
    'error.title': 'Une erreur est survenue',
    'error.info': "Une erreur s'est produite. Veuillez recharger la page et réessayer.",
    'error.button': 'Réessayer',
    'loading.text': 'Chargement...',
    'mainmenu.title': 'Bienvenue',
    'mainmenu.button.newgame': 'Cliquer pour jouer',
    'navbar.language.label': 'Changer de langue',
    'navbar.color.label': 'Changer le thème de couleurs',
    'game.question.effectiveness': '%s utilise %s',
    'game.status.fainted': '%s est K.O.',
    'game.status.switched': 'Vas-y ! %s',
    'gameover.title': 'Partie terminée',
    'gameover.text.blackout': "vous n'avez plus de Pokémon en état de combattre...",
    'gameover.text.score': 'votre score final est',
    'gameover.button.newgame': 'Réessayer',
    'gameover.button.mainmenu': 'Menu principal',
    'score.label': 'Score',
    'types.effectiveness.noeffect': 'Aucun effet',
    'types.effectiveness.noteffective': 'Pas très efficace',
    'types.effectiveness.effective': 'Efficace',
    'types.effectiveness.supereffective': 'Super efficace',
    'mainmenu.difficulty.simple': 'Facile',
    'mainmenu.difficulty.expert': 'Expert',
  },
  it: {
    'error.title': 'Qualcosa è andato storto',
    'error.info': 'Si è verificato un errore. Ricarica la pagina e riprova.',
    'error.button': 'Riprova',
    'loading.text': 'Caricamento...',
    'mainmenu.title': 'Benvenuto',
    'mainmenu.button.newgame': 'Tocca per giocare',
    'navbar.language.label': 'Cambia lingua',
    'navbar.color.label': 'Cambia combinazione di colori',
    'game.question.effectiveness': '%s ha usato %s',
    'game.status.fainted': '%s è esausto',
    'game.status.switched': 'Vai! %s',
    'gameover.title': 'Game Over',
    'gameover.text.blackout': 'non hai più Pokémon in grado di combattere...',
    'gameover.text.score': 'il tuo punteggio finale è',
    'gameover.button.newgame': 'Riprova',
    'gameover.button.mainmenu': 'Menu principale',
    'score.label': 'Punteggio',
    'types.effectiveness.noeffect': 'Nessun effetto',
    'types.effectiveness.noteffective': 'Non molto efficace',
    'types.effectiveness.effective': 'Efficace',
    'types.effectiveness.supereffective': 'Superefficace',
    'mainmenu.difficulty.simple': 'Facile',
    'mainmenu.difficulty.expert': 'Esperto',
  },
  ja: {
    'error.title': '問題が発生しました',
    'error.info': 'エラーが発生しました。ページを再読み込みしてもう一度お試しください。',
    'error.button': 'もう一度試す',
    'loading.text': '読み込み中...',
    'mainmenu.title': 'ようこそ',
    'mainmenu.button.newgame': 'タップしてスタート',
    'navbar.language.label': '言語を変更',
    'navbar.color.label': 'カラーテーマを変更',
    // %s tokens keep explicit surrounding spaces so useLocalization's space-split
    // templating can still find them, even though natural Japanese has no spaces.
    'game.question.effectiveness': '%s は %s を繰り出した',
    'game.status.fainted': '%s は ひんしになった',
    'game.status.switched': 'いけ！ %s',
    'gameover.title': 'ゲームオーバー',
    'gameover.text.blackout': '戦えるポケモンがいなくなった...',
    'gameover.text.score': '最終スコアは',
    'gameover.button.newgame': 'もう一度挑戦',
    'gameover.button.mainmenu': 'メインメニュー',
    'score.label': 'スコア',
    'types.effectiveness.noeffect': 'こうかがないようだ',
    'types.effectiveness.noteffective': 'いまひとつのようだ',
    'types.effectiveness.effective': 'こうかは普通だ',
    'types.effectiveness.supereffective': 'こうかはばつぐんだ',
    'mainmenu.difficulty.simple': 'かんたん',
    'mainmenu.difficulty.expert': 'エキスパート',
  },
  ko: {
    'error.title': '문제가 발생했습니다',
    'error.info': '오류가 발생했습니다. 페이지를 새로고침한 후 다시 시도해 주세요.',
    'error.button': '다시 시도',
    'loading.text': '불러오는 중...',
    'mainmenu.title': '환영합니다',
    'mainmenu.button.newgame': '탭하여 시작',
    'navbar.language.label': '언어 변경',
    'navbar.color.label': '색상 테마 변경',
    'game.question.effectiveness': '%s 이(가) %s 을(를) 사용했다',
    'game.status.fainted': '%s 이(가) 쓰러졌다',
    'game.status.switched': '가랏! %s',
    'gameover.title': '게임 오버',
    'gameover.text.blackout': '싸울 수 있는 포켓몬이 없습니다...',
    'gameover.text.score': '최종 점수는',
    'gameover.button.newgame': '다시 시작',
    'gameover.button.mainmenu': '메인 메뉴',
    'score.label': '점수',
    'types.effectiveness.noeffect': '효과가 없다',
    'types.effectiveness.noteffective': '효과가 별로인 듯하다',
    'types.effectiveness.effective': '효과가 보통이다',
    'types.effectiveness.supereffective': '효과가 굉장하다',
    'mainmenu.difficulty.simple': '쉬움',
    'mainmenu.difficulty.expert': '전문가',
  },
};
