name: Run Tests

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VITE_POKE_API_URL: https://api.pokequiz.me/api/v1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run test:unit:ci

      - name: Run E2E Tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          run: npm run test:headless