name: Run Tests

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VITE_POKE_API_URL: https://api.pokequiz.me/api/v1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run test:unit:ci

      - name: Run E2E Tests
        uses: cypress-io/github-action@v6
        with:
          record: true
          start: npm run dev

      - name: Archive E2E Results
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: react-pokemon-quiz/react-pokemon-quiz/cypress/screenshots
